import { library } from '@fortawesome/fontawesome-svg-core';

// DUO TONE PRO ICONS! LEAF HEARTS!
import {
  faSword,
  faShieldVirus,
  faTurtle,
  faSnowflake,
  faRabbitFast,
  faFire,
  faDragon,
  faHatWizard,
  faEnvelope,
  faSwords,
  faHelmetBattle,
  faMapMarked,
  faEyeEvil,
  faDna,
  faPaw,
  faEye,
  faHandSpock,
  faUnicorn,
  faFaceSmileHorns,
  faBat,
  faMonkey,
  faHorseHead,
  faInfoCircle,
  faRabbitRunning,
  faRoad,
  faHeadSideBrain,
  faChartNetwork,
  faTimes,
  faNetworkWired,
  faWallet,
  faUsersCrown,
  faFile,
  faCoin,
  faCoins,
  faQuestionSquare,
  faFunction,
  faCode,
  faTrophy,
  // faLevelUp, // should be in here, but are not!
   // not working either???
  // faTrophyAlt
} from '@fortawesome/pro-duotone-svg-icons';

import {
  faHome,
  faBars,
  faChevronDown,
  faHandHoldingUsd,
  faMoneyBill,
  faDollarSign,
  faUser,
  faUsers,
  faRunning,
  faBaby,
  faCog,
  // faFaceSmileHorns, version 6
  faTree,
  faQuestion,

} from '@fortawesome/free-solid-svg-icons'


import {
  faGithubAlt,
  faGithub,
  faGoogle,
  faFacebook,
  faTwitter,
  faYoutube,
  faInstagram,
  faLinkedin,
  faDiscord,
  faEthereum,
  faReact,
  faNodeJs,
  faNode
} from '@fortawesome/free-brands-svg-icons';


import {

  faFlaskPoison,
  faFlushed,
  faSnooze,
  faLeafHeart,
} from '@fortawesome/pro-light-svg-icons';


import {
  faShield,
  faFaceDizzy,
} from '@fortawesome/pro-thin-svg-icons';

library.add(
  faGithubAlt,
  faGoogle,
  faFacebook,
  faTwitter,
  faGithub,
  faHome,
  faBars,
  faChevronDown,
  faHandHoldingUsd,
  faMoneyBill,
  faDollarSign,
  faYoutube,
  faInstagram,
  faLinkedin,
  faDiscord,
  faUser,
  faInfoCircle,
  faFire,
  faDragon,
  faDna,
  faRunning,
  faBaby,
  faCog,
  faSnowflake,
  faLeafHeart,
  faFlaskPoison,
  faSword,
  faShieldVirus,
  faShield,
  faRabbitFast,
  faTree,
  faFlushed,
  faFaceDizzy,
  faSnooze,
  faTurtle,
  faHatWizard,
  faEnvelope,
  faSwords,
  faHelmetBattle,
  faMapMarked,
  faEyeEvil,
  faPaw,
  faEye,
  faHandSpock,
  faCoins,
  faUnicorn,
  faFaceSmileHorns, // version 6, broke other things like user circle
  faBat,
  faMonkey,
  faHorseHead,
  faRabbitRunning,
  faRoad,
  faHeadSideBrain,
  faChartNetwork,
  faTimes,
  faQuestion,
  faQuestionSquare,
  faNetworkWired,
  faEthereum,
  faWallet,
  faUsersCrown,
  faFile,
  faCoin,
  faUsers,
  faTrophy,
  faReact,
  faFunction,
  faNodeJs,
  faNode,
  faCode
);
